name: food_delivery_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flutter_credit_card: ^4.1.0
  intl: ^0.17.0
  collection: ^1.19.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  flutter_stripe: ^11.4.0
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  video_player: ^2.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
    - assets/animation/