name: food_delivery_app
description: "A new Flutter project for a food delivery service."

# Prevents accidental publishing to pub.dev
publish_to: 'none'  

# Version and build number
version: 1.0.0+1

# Flutter & Dart SDK version requirement
environment:
  sdk: ">=3.7.0 <4.0.0"

# Dependencies required for the app
dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1  # Custom fonts
  flutter_svg: ^2.0.10  # For SVG images

  # State Management
  provider: ^6.1.2

  # Networking
  http: ^1.2.1  # For API calls

  # Local Storage
  shared_preferences: ^2.2.2  # Save user preferences locally

  # # Firebase Services (Optional - Only if you plan to use Firebase)
  # firebase_core: ^2.27.0
  # firebase_auth: ^4.17.9
  # cloud_firestore: ^4.15.9
  # firebase_storage: ^11.6.9  # For storing images

  # Navigation & Routing
  go_router: ^14.0.1  # Advanced navigation handling

  # Image Handling
  image_picker: ^1.0.8  # To pick images from gallery/camera

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Linting for better code quality

# Flutter-specific settings
flutter:
  uses-material-design: true

  # Assets
  assets:
    # - assets/images/
    # - assets/icons/

  # Custom Fonts
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
